### ISSUE TITLE
pangocairo used, but not checked

### ISSUE THREAD

**Issue by olafhering** [awarnke/crystal-facet-uml#2]
I think `CMakeLists.txt` requires `pkg_search_module(PANGOCAIRO REQUIRED pangocairo)`, and the usage of the resulting `PANGOCAIRO_LIBRARIES` + `PANGOCAIRO_INCLUDE_DIRS`.
See [failures](https://build.opensuse.org/package/show/devel:tools/crystal_facet_uml) here.

**Comment by awarnke** [comment]
Hi Olaf,

thank you for checking the issue and for proposing a fix.

I guess you refer to this issue here:

[  171s] In file included from /usr/include/pango-1.0/pango/pango-font.h:25:0,
[  171s]                  from /usr/include/pango-1.0/pango/pango-attributes.h:25,
[  171s]                  from /usr/include/pango-1.0/pango/pango.h:25,
[  171s]                  from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
[  171s]                  from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
[  171s]                  from /usr/include/gtk-3.0/gdk/gdk.h:32,
[  172s]                  from /usr/include/gtk-3.0/gtk/gtk.h:30,
[  172s]                  from /home/abuild/rpmbuild/BUILD/crystal-facet-uml-1.16.1/gui/include/gui_resources.h:12,
[  172s]                  from /home/abuild/rpmbuild/BUILD/crystal-facet-uml-1.16.1/gui/include/gui_simple_message_to_user.h:13,
[  172s]                  from /home/abuild/rpmbuild/BUILD/crystal-facet-uml-1.16.1/gui/include/gui_clipboard.h:12,
[  172s]                  from /home/abuild/rpmbuild/BUILD/crystal-facet-uml-1.16.1/gui/source/gui_clipboard.c:3:
[  172s] /usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
[  172s]  #include <hb.h>
[  172s]           ^~~~~~
[  172s] compilation terminated.

I tried to realize your proposal:

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3efa09ca..fd637e2b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -46,6 +46,9 @@ INCLUDE_DIRECTORIES(${GTK3_INCLUDE_DIRS})
 #MESSAGE("GTK3:    ${GTK3_CFLAGS}")
 #MESSAGE("GTK3:    ${GTK3_CFLAGS_OTHER}")
 
+pkg_search_module(PANGOCAIRO REQUIRED pangocairo)
+INCLUDE_DIRECTORIES(${PANGOCAIRO_INCLUDE_DIRS})
+
 FILE(GLOB commonSource gui/source/*.c
                        gui/source/sketch_area/*.c
                        trace/source/*.c
@@ -95,7 +98,7 @@ SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11 -D_XOPEN_SOURCE=700 -O2 -pedantic -
 # ==== ==== ==== ==== ==== ==== ==== ==== C-Code crystal_facet_uml Linker Settings ==== ==== ==== ==== ==== ==== ==== ====
 
 ADD_EXECUTABLE(crystal_facet_uml ${appSource} ${commonSource} ${COMPILE_IN_SOURCE_FILE})
-TARGET_LINK_LIBRARIES(crystal_facet_uml ${GTK3_LIBRARIES} ${GLIB2_LIBRARIES} ${SQLITE3_LIBRARIES} m)
+TARGET_LINK_LIBRARIES(crystal_facet_uml ${GTK3_LIBRARIES} ${GLIB2_LIBRARIES} ${PANGOCAIRO_LIBRARIES} ${SQLITE3_LIBRARIES} m)
 SET_TARGET_PROPERTIES(crystal_facet_uml PROPERTIES LINKER_LANGUAGE C)
 
 # ==== ==== ==== ==== ==== ==== ==== ==== C-Code unittest Compiler Settings ==== ==== ==== ==== ==== ==== ==== ====
lines 1-23/23 (END)

and it still compiles on my system. Let's see if this solves the issue at https://build.opensuse.org/package/show/devel:tools/crystal_facet_uml

Andi

**Comment by awarnke** [comment]
A possible fix is commited to github as version 1.26.0 and uploaded to my home-area on opensuse build server: https://build.opensuse.org/package/show/home:awarnke/crystal_facet_uml
